Fnymmm/add token generator
SwissLife-OSS/IdOps pull request #61
Opened 2023-04-19 13:17 UTC by fnymmm

Added the ability to generate Tokens based on ClientId and SecretId.
The secret in plain text is being kept server side.

-Secret has to be generated with the "save secret" option enabled and be published.

2023-04-19 15:25 UTC, PascalSenn reviewed
I partially reviewed this.
But i dont understand a few things.

- What do we need asymetric encryption for?
- Why do we not just use the Dataprotector API if we really need it?
- Why do we store the tokens?
and a few more

2023-04-19 15:25 UTC, PascalSenn commented on src/Server/src/AuthTokenGenerator/Certification/CertificateDataProtector.cs
> +    public class CertificateDataProtector : IDataProtector
What do we need this for?

2023-04-19 15:25 UTC, PascalSenn commented on src/Server/src/AuthTokenGenerator/Certification/IDataProtector.cs
> +        byte[] UnProtect(byte[] data);
Unprotect

2023-04-19 15:25 UTC, PascalSenn commented on src/Server/src/AuthTokenGenerator/DefaultShellService.cs
> +
Nope => make it async

2023-04-19 15:25 UTC, PascalSenn commented on src/Server/src/AuthTokenGenerator/Certification/SymmetricEncryption.cs
> +                    return new AesManaged()
Isnt this deprecated?

2023-04-19 15:25 UTC, PascalSenn commented on src/Server/src/AuthTokenGenerator/DefaultShellService.cs
> +    public class DefaultShellService : IDefaultShellService
What?

2023-04-19 15:25 UTC, PascalSenn commented on src/Server/src/AuthTokenGenerator/IdentityService.cs
> +            if (request.GrantType == "client_credentials")
Create methods for each GranType that you want to process here.

2023-04-19 15:25 UTC, PascalSenn commented on src/Server/src/GraphQL/Client/ClientMutations.cs
> +        public async Task<AddClientSecretPayload> AddClientSecretAsync(AddClientSecretRequest input,
Please do not change the formatting

2023-04-20 06:57 UTC, fnymmm commented on src/Server/src/AuthTokenGenerator/IdentityService.cs
> +                response = await _httpClientWrapper.RequestClientCredentialsTokenAsync(
I created this wrapper so i can mock it, httpClients use extention methods for these requests://

2023-04-25 07:33 UTC, PascalSenn requested changes
It looks much better now. I made a few comments.

I think we still carry too much from Boost into IdOps. For example, the TokenModel. Do we need all these properties? What does the UI need? If we pass it out through the GraphQL API, then the frontend should have a requirement for it. Otherwise, it's probably not necessary.

2023-04-25 07:33 UTC, PascalSenn commented on src/Server/src/GraphQL/Client/TokenRequestDataResultFactory.cs
> +            client.AllowedScopes.ToList().ConvertAll(clientScope => clientScope.Id );
client.AllowedScopes.Select(x => x.Id).ToList() ?

2023-04-25 07:33 UTC, PascalSenn commented on src/Server/src/GraphQL/Client/TokenRequestDataResultFactory.cs
> +            client.AllowedScopes.ToList().ConvertAll(clientScope => clientScope.Id );
Maybe it doesnt even need to be a `ToList` when `scopeService` accepts a `IEnumerable<Guid>`

2023-04-25 07:33 UTC, PascalSenn commented on src/Server/src/AuthTokenGenerator/IdentityService.cs
> +                "client_credentials" => await RequestClientCredentialTokenAsync(request, disco),
What do we do with `authorization_code`? Do we already have a plan for this?

2023-04-25 07:33 UTC, PascalSenn commented on src/Server/src/GraphQL/Client/SaveClientPayload.cs
> +
Empty lines

2023-06-22 06:54 UTC, closed without merging

2023-06-22 06:54 UTC, fnymmm commented
everything merged with other pr